services:
  - type: web
    name: exotel-voicebot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: SARVAMAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
